# Generated by Django 5.1.1 on 2024-09-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, upload_to='blogs/videos', verbose_name='Видео по статье'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(verbose_name='Содержание статьи'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='focus',
            field=models.CharField(blank=True, max_length=250, verbose_name='Напрпвленность статьи'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='labor_protection',
            field=models.TextField(blank=True, verbose_name='Охрана труда(связанная со статьей)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название статьи'),
        ),
    ]
