# Generated by Django 5.1.1 on 2024-09-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_video_alter_blog_description_alter_blog_focus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video',
        ),
    ]
