# Generated by Django 5.1.1 on 2024-09-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название оборудования')),
                ('description', models.CharField(max_length=100, verbose_name='Назначение')),
                ('image', models.ImageField(blank=True, upload_to='equipments/images/', verbose_name='Изображение оборудования')),
                ('manual', models.TextField(blank=True, verbose_name='Инструкция')),
                ('url', models.URLField(blank=True, verbose_name='Страница в интернете')),
                ('servicebility', models.BooleanField(verbose_name='Работоспособность')),
                ('defect', models.CharField(max_length=100, verbose_name='Неполадки')),
            ],
        ),
    ]
