# Generated by Django 5.1.1 on 2024-09-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название навыка')),
                ('description', models.CharField(max_length=250, verbose_name='Описание навыка')),
                ('image', models.ImageField(upload_to='skills/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
