# Generated by Django 5.1.1 on 2024-09-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(blank=True, upload_to='skills/images'),
        ),
    ]
