# Generated by Django 5.1.1 on 2024-09-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skills_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='fio',
            field=models.CharField(default=1, max_length=50, verbose_name='Имя подсобного рабочего'),
            preserve_default=False,
        ),
    ]
