# Generated by Django 5.1.1 on 2024-09-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='numbers_of_workers',
            field=models.IntegerField(default=1, verbose_name='Количество человек на задание'),
            preserve_default=False,
        ),
    ]
