# Generated by Django 5.1.1 on 2024-09-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_works_numbers_of_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='numbers_of_workers',
            field=models.IntegerField(blank=True, verbose_name='Количество человек на задание'),
        ),
    ]
